# Generated by Django 5.2.8 on 2026-07-18 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('encounters', '0006_seed_more_complaints'),
        ('users', '0003_add_whatsapp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=8)),
                ('external_facility_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField()),
                ('reason_ar', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('notes_ar', models.TextField(blank=True)),
                ('referral_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_accepted', to='doctors.doctorprofile')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='users.patientprofile')),
                ('referring_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='doctors.doctorprofile')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='doctors.specialty')),
                ('target_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'), models.Index(fields=['referring_doctor', 'status'], name='referrals_r_referri_3a8e44_idx')],
            },
        ),
    ]
