# Generated by Django 5.2.8 on 2026-06-19 12:45

import apps.medical_records.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('medical_records', '0002_initial'),
        ('users', '0003_add_whatsapp_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], db_index=True, default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.laborder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('result_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.medical_records.models.lab_order_result_path)),
                ('interpretation', models.CharField(blank=True, max_length=500)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lab_results', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='medical_records.laborder')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='medical_records.laborderitem')),
            ],
            options={
                'ordering': ['order_item', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='medical_rec_patient_60e025_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['doctor', 'status'], name='medical_rec_doctor__ad6a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'created_at'], name='medical_rec_status_819c76_idx'),
        ),
    ]
