# Generated by Django 5.2.8 on 2026-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_laborder_laborderitem_laborderresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='laborder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
