# Generated by Django 5.2.8 on 2026-06-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('medical_records', '0004_laborder_cancellation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='encounters.encounter'),
        ),
    ]
