# Generated by Django 5.2.8 on 2026-06-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_prescription_cancellation_fields'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.dosageform'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.dosagepattern'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage_strength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='medications.medication'),
        ),
    ]
