# Generated by Django 5.2.8 on 2026-06-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_diagnosiscategory_diagnosis_icd10_code_and_more'),
        ('medical_records', '0007_prescriptionitem_dosage_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='encounters.diagnosis'),
        ),
    ]
