# Generated by Django 5.2.8 on 2026-06-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_medicalrecord_diagnosis_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('SERUM', 'Serum'), ('WHOLE_BLOOD', 'Whole Blood'), ('URINE', 'Urine'), ('CSF', 'CSF'), ('SWAB', 'Swab'), ('STOOL', 'Stool'), ('OTHER', 'Other')], max_length=20)),
                ('sample_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('collected_at', models.DateTimeField()),
                ('sent_to_lab_at', models.DateTimeField(blank=True, null=True)),
                ('received_at_lab', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_collection', to='medical_records.laborder')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
