# Generated by Django 5.2.8 on 2026-08-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_samplecollection'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='radiology_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='radiology.radiologyorder'),
        ),
    ]
