# Generated by Django 5.2.8 on 2026-09-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('root_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], db_index=True, max_length=12)),
                ('account_type', models.CharField(blank=True, choices=[('RECEIVABLE', 'Receivable'), ('PAYABLE', 'Payable'), ('CASH', 'Cash'), ('BANK', 'Bank'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TAX', 'Tax'), ('INVENTORY', 'Inventory'), ('COGS', 'Cost of goods sold'), ('FIXED_ASSET', 'Fixed asset'), ('ACCUMULATED_DEPRECIATION', 'Accumulated depreciation'), ('EQUITY', 'Equity'), ('PATIENT_DEPOSIT', 'Patient deposit'), ('CONTRACTUAL_ADJUSTMENT', 'Contractual adjustment'), ('WRITE_OFF', 'Write off'), ('ROUND_OFF', 'Round off'), ('DEFERRED_REVENUE', 'Deferred revenue')], db_index=True, max_length=32)),
                ('is_group', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='EGP', max_length=8)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(db_index=True, max_length=64)),
                ('qualifier', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_map_entries', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account map entry',
                'verbose_name_plural': 'Account map entries',
                'ordering': ['purpose', 'qualifier'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='fiscal_year_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSED', 'Soft closed'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_account_code'),
        ),
        migrations.AddConstraint(
            model_name='accountmap',
            constraint=models.UniqueConstraint(fields=('purpose', 'qualifier'), name='uniq_account_map'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='period_end_after_start'),
        ),
    ]
