# Generated by Django 5.2.8 on 2026-09-07 18:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('billing', '0004_invoiceitem_uniq_invoice_item_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_date', models.DateField(db_index=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.period')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.journalentry')),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('party_type', models.CharField(blank=True, default='', max_length=16)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.journalentry')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='billing.invoiceitem')),
            ],
            options={
                'ordering': ['entry_id', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__3d844c_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='uniq_je_idempotency'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['party_type', 'party_id'], name='accounting__party_t_3fe2d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('entry', 'line_no'), name='uniq_journal_line_no'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='jl_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit', 0), models.Q(('credit', 0), _negated=True)), models.Q(models.Q(('debit', 0), _negated=True), ('credit', 0)), _connector='OR'), name='jl_exactly_one_side'),
        ),
    ]
