# Generated by Django 5.2.8 on 2026-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('APPT_CONFIRMED', 'Appointment confirmed'), ('APPT_CANCELLED', 'Appointment cancelled'), ('APPT_BOOKED', 'Appointment booked'), ('APPT_REMINDER', 'Appointment reminder'), ('ABSENCE', 'Doctor absence'), ('WAITLIST_OPEN', 'Waitlist slot opened'), ('FOLLOWUP', 'Follow-up'), ('REVIEW', 'Review request'), ('GENERIC', 'Notification')], default='GENERIC', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('body_ar', models.TextField(blank=True)),
                ('channels_sent', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
