# Generated by Django 5.2.8 on 2026-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('APPT_CONFIRMED', 'Appointment confirmed'), ('APPT_CANCELLED', 'Appointment cancelled'), ('APPT_BOOKED', 'Appointment booked'), ('APPT_REMINDER', 'Appointment reminder'), ('ABSENCE', 'Doctor absence'), ('WAITLIST_OPEN', 'Waitlist slot opened'), ('FOLLOWUP', 'Follow-up'), ('REVIEW', 'Review request'), ('GENERIC', 'Notification'), ('LAB_ORDER_CREATED', 'Lab order created'), ('LAB_RESULT_AVAILABLE', 'Lab result available'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('LAB_RESULT_REVIEWED', 'Lab result reviewed')], default='GENERIC', max_length=32),
        ),
    ]
