# Generated by Django 5.2.8 on 2026-08-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_verb_lab_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('APPT_CONFIRMED', 'Appointment confirmed'), ('APPT_CANCELLED', 'Appointment cancelled'), ('APPT_BOOKED', 'Appointment booked'), ('APPT_REMINDER', 'Appointment reminder'), ('ABSENCE', 'Doctor absence'), ('WAITLIST_OPEN', 'Waitlist slot opened'), ('FOLLOWUP', 'Follow-up'), ('REVIEW', 'Review request'), ('GENERIC', 'Notification'), ('LAB_ORDER_CREATED', 'Lab order created'), ('LAB_ORDER_CANCELLED', 'Lab order cancelled'), ('LAB_RESULT_AVAILABLE', 'Lab result available'), ('LAB_RESULT_CRITICAL', 'Critical lab result'), ('LAB_RESULT_REVIEWED', 'Lab result reviewed'), ('REFERRAL_CREATED', 'New referral'), ('REFERRAL_ACCEPTED', 'Referral accepted'), ('REFERRAL_COMPLETED', 'Referral completed'), ('REFERRAL_CANCELLED', 'Referral cancelled'), ('PROCEDURE_SCHEDULED', 'Procedure scheduled'), ('PROCEDURE_COMPLETED', 'Procedure completed'), ('PROCEDURE_CANCELLED', 'Procedure cancelled'), ('RADIOLOGY_ORDER_CREATED', 'Radiology order created'), ('RADIOLOGY_ORDER_COMPLETED', 'Radiology scan completed'), ('RADIOLOGY_ORDER_REPORTED', 'Radiology report available'), ('RADIOLOGY_ORDER_CANCELLED', 'Radiology order cancelled'), ('PATIENT_SCAN_UPLOADED', 'Patient uploaded a scan'), ('APPT_EXPIRED', 'Booking expired'), ('APPT_NO_SHOW', 'Marked as no-show')], default='GENERIC', max_length=32),
        ),
    ]
