# Generated by Django 5.2.8 on 2026-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='PENDING', max_length=12)),
                ('appointment_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WALK_IN', 'Walk-in'), ('EMERGENCY', 'Emergency'), ('FOLLOW_UP', 'Follow-up')], default='SCHEDULED', max_length=12)),
                ('priority', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_date', models.DateField()),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('SCHEDULED', 'Scheduled'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed')], default='SUGGESTED', max_length=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_date_from', models.DateField()),
                ('desired_date_to', models.DateField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=12)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notify_expires_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
