# Generated by Django 5.2.8 on 2026-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
