# Generated by Django 5.2.8 on 2026-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile_chronic_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
