# Generated by Django 5.2.8 on 2026-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
