# Generated by Django 5.2.8 on 2026-08-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('encounters', '0006_seed_more_complaints'),
        ('users', '0003_add_whatsapp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('modality', models.CharField(choices=[('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('PET', 'PET Scan'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('body_part', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('accession_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('study_name', models.CharField(blank=True, max_length=255)),
                ('study_name_ar', models.CharField(blank=True, max_length=255)),
                ('clinical_reason', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], db_index=True, default='ORDERED', max_length=12)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders', to='doctors.doctorprofile')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_orders', to='users.patientprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='radiology.radiologytemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='radiology_r_patient_e5aa80_idx'), models.Index(fields=['doctor', 'status'], name='radiology_r_doctor__03dc07_idx'), models.Index(fields=['status', 'created_at'], name='radiology_r_status_fcc68a_idx')],
            },
        ),
    ]
