# Generated by Django 5.2.8 on 2026-06-22 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('users', '0003_add_whatsapp_enabled'),
        ('vital_signs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('CARDIAC', 'Cardiac'), ('RESPIRATORY', 'Respiratory'), ('GI', 'Gastrointestinal'), ('MUSCULOSKELETAL', 'Musculoskeletal'), ('NEUROLOGICAL', 'Neurological'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('CARDIAC', 'Cardiac'), ('RESPIRATORY', 'Respiratory'), ('GI', 'Gastrointestinal'), ('MUSCULOSKELETAL', 'Musculoskeletal'), ('NEUROLOGICAL', 'Neurological'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('encounter_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AMENDED', 'Amended')], db_index=True, default='DRAFT', max_length=12)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('chief_complaint_ar', models.CharField(blank=True, max_length=255)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('examination_findings', models.TextField(blank=True)),
                ('examination_findings_ar', models.TextField(blank=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('treatment_plan_ar', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='appointments.appointment')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='encounters.diagnosis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_encounters', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='users.patientprofile')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_by', to='encounters.encounter')),
                ('vitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='vital_signs.vitalsigns')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_current'], name='encounters__patient_4f7e89_idx'), models.Index(fields=['doctor', 'status'], name='encounters__doctor__ea1c09_idx')],
            },
        ),
    ]
