# Generated by Django 5.2.8 on 2026-06-22 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_seed_complaints_diagnoses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
