# Generated by Django 5.2.8 on 2026-08-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='EGP', max_length=8),
        ),
    ]
