# Generated by Django 5.2.8 on 2026-09-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_backfill_currency_egp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source_type', 'source_id'), name='uniq_invoice_item_source'),
        ),
    ]
