# Generated by Django 5.2.8 on 2026-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_invoiceitem_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='source_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('LAB_ORDER', 'Lab order'), ('PROCEDURE', 'Procedure'), ('RADIOLOGY_ORDER', 'Radiology order')], default='APPOINTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='item_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_TEST', 'Lab test'), ('PROCEDURE', 'Procedure'), ('RADIOLOGY', 'Radiology'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
