# Generated by Django 5.2.8 on 2026-09-09 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journal_immutability_trigger'),
        ('billing', '0007_alter_invoiceitem_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('till_id', models.CharField(db_index=True, default='MAIN', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(default='EGP', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_shift_variances', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.cashiershift'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.cashiershift'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['cashier', 'status'], name='billing_cas_cashier_81a65d_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['status', 'opened_at'], name='billing_cas_status_f9b761_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cashier',), name='uniq_open_shift_per_cashier'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('till_id',), name='uniq_open_shift_per_till'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float__gte', Decimal('0.00'))), name='shift_opening_float_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('counted_amount__isnull', True), ('counted_amount__gte', Decimal('0.00')), _connector='OR'), name='shift_counted_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('variance__isnull', True), ('variance', Decimal('0.00')), models.Q(models.Q(('variance_reason_code', ''), _negated=True), ('approved_by__isnull', False)), _connector='OR'), name='shift_variance_requires_reason_and_approval'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_at__isnull', False), ('expected_amount__isnull', False), ('counted_amount__isnull', False), ('variance__isnull', False)), _connector='OR'), name='closed_shift_is_complete'),
        ),
    ]
