# Generated by Django 5.2.8 on 2026-09-13 22:06
#
# Financial roadmap Task 14 — a real gapless invoice number, backed by
# InvoiceNumberSequence rather than a DB SEQUENCE (see services.py's
# `allocate_invoice_number` docstring for why). This migration also backfills
# every pre-existing invoice with the exact display number it already had
# (`INV-{pk:05d}`, the old @property's format) so nothing already shown to a
# patient or printed on a receipt changes — see backfill_invoice_numbers below.
from django.conf import settings
from django.db import migrations, models


def backfill_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    InvoiceNumberSequence = apps.get_model("billing", "InvoiceNumberSequence")

    max_pk = 0
    for invoice_id in Invoice.objects.order_by("pk").values_list("pk", flat=True):
        Invoice.objects.filter(pk=invoice_id).update(invoice_number=f"INV-{invoice_id:05d}")
        max_pk = invoice_id

    # Seed the sequence so the *first* newly-allocated number continues right
    # after the highest pre-existing pk-derived number, guaranteeing no new
    # invoice_number can ever collide with a backfilled one.
    InvoiceNumberSequence.objects.update_or_create(
        scope="default", defaults={"last_value": max_pk},
    )


def noop_reverse(apps, schema_editor):
    """Deliberately a no-op: reversing would blank out real, already-issued
    invoice numbers, which is exactly the kind of destructive rewrite of
    posted financial history this project's conventions forbid."""


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_protect_financial_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(default='default', max_length=32, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_invoice_numbers, noop_reverse),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('invoice_number',), name='uniq_invoice_number'),
        ),
    ]
