# Generated by Django 5.2.8 on 2026-09-14 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_cash_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('ISSUE_REFUND', 'Issue refund'), ('ISSUE_CREDIT_NOTE', 'Issue credit note'), ('RECORD_CASH_MOVEMENT', 'Record cash movement'), ('RECORD_PAYMENT', 'Record payment')], max_length=32)),
                ('key', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=16)),
                ('result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'operation', 'key'), name='uniq_idempotent_request'), models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='idempotent_request_key_required')],
            },
        ),
    ]
