# Generated by Django 5.2.8 on 2026-06-22 06:47

import apps.ai_scribe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('medical_records', '0004_laborder_cancellation_fields'),
        ('users', '0003_add_whatsapp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(upload_to=apps.ai_scribe.models.session_audio_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBING', 'Transcribing'), ('EXTRACTING', 'Extracting'), ('READY', 'Ready for review'), ('FAILED', 'Failed'), ('COMMITTED', 'Committed')], db_index=True, default='PENDING', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='appointments.appointment')),
                ('committed_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='medical_records.prescription')),
                ('committed_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='medical_records.medicalrecord')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='users.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='ai_scribe_s_patient_05cf9d_idx'), models.Index(fields=['doctor', 'status'], name='ai_scribe_s_doctor__2ce2b8_idx')],
            },
        ),
    ]
