# Generated by Django 5.2.8 on 2026-06-08 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorabsence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treating_doctors', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorabsence',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.specialty'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='doctors.specialtycategory'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='source_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='doctors.workingschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatient',
            unique_together={('doctor', 'patient')},
        ),
        migrations.AlterUniqueTogether(
            name='workingschedule',
            unique_together={('doctor', 'weekday', 'start_time', 'valid_from')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'date', 'status'], name='doctors_tim_doctor__02f952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'start_datetime')},
        ),
    ]
