# Generated by Django 5.2.8 on 2026-08-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='full_name_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
