# Generated by Django 5.2.8 on 2026-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_copy_full_name_ar_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='full_name_ar',
        ),
    ]
