name: CI/CD Pipeline to VPS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python -m pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment script via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash /var/www/clinic_app/deploy/deploy.sh

      - name: Send Email Confirmation
        if: success()
        continue-on-error: true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Deployment Successful"
          body: "The latest commit has been successfully deployed to 213.199.47.114."
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: GitHub Actions
